### ISSUE TITLE
Problems to load the package

### ISSUE THREAD

**Issue by henryhamon** [UGroup/Atom-COS-Studio#33]
[Enter steps to reproduce below:]
1. ... I just follow the instructions on Readme, and try to run atom...
2. ...What I've missed to install?

**Atom Version**: 1.5.4
**System**: Unknown Windows Version
**Thrown From**: [Atom-COS-Studio](https://github.com/UGroup/Atom-COS-Studio) package, v0.5.0
### Stack Trace

Failed to load the Atom-COS-Studio package

```
At Cannot find module 'fsplus'

Error: Cannot find module 'fsplus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/henry.pereira/.atom/packages/Atom-COS-Studio/lib/Atom-COS-Studio-view.coffee:4:5)
    at Object.<anonymous> (file:///C:/Users/henry.pereira/.atom/packages/Atom-COS-Studio/lib/Atom-COS-Studio-view.coffee:1:1)
    at Module._compile (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/henry.pereira/.atom/packages/Atom-COS-Studio/lib/Atom-COS-Studio.coffee:1:21)
    at Object.<anonymous> (file:///C:/Users/henry.pereira/.atom/packages/Atom-COS-Studio/lib/Atom-COS-Studio.coffee:1:1)
    at Module._compile (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:720:27)
    at C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:116:28
    at Package.module.exports.Package.measure (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\atom-environment.js:684:21)
    at module.exports (C:\Users\henry.pereira\AppData\Local\atom\app-1.5.4\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/henry.pereira/AppData/Local/atom/app-1.5.4/resources/app.asar/static/index.js:86:5)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Atom-COS-Studio, v0.5.0

# Dev
No dev packages
```

**Comment by mebays** [comment]
I have the same issue did anyone ever solve this? 

Atom version 1.14.3
Cache version 2015.2
Windows 7

**Comment by henryhamon** [comment]
@mebays noops
I guess this project was discontinued... 
Now I'm using this [cache-dev-project](https://github.com/ZitRos/cache-dev-project)
