### ISSUE TITLE
Failed to load the Atom-COS-Studio package

### ISSUE THREAD

**Issue by mebays** [UGroup/Atom-COS-Studio#36]
[Enter steps to reproduce:]

1. Followed install instructions.
2. Went into Atom-COS-Studio and used npm install to install dependency modules.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [Atom-COS-Studio](https://github.com/UGroup/Atom-COS-Studio) package 0.5.0

### Stack Trace

Failed to load the Atom-COS-Studio package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/Atom-COS-Studio/lib/view/namespace-list-view.coffee:1:1)
    at /packages/Atom-COS-Studio/lib/view/namespace-list-view.coffee:3:7
    at /packages/Atom-COS-Studio/lib/view/namespace-list-view.coffee:13:14)
    at /packages/Atom-COS-Studio/lib/view/namespace-list-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Atom-COS-Studio/lib/view/select-namespace-view.coffee:2:19)
    at /packages/Atom-COS-Studio/lib/view/select-namespace-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Atom-COS-Studio/lib/Atom-COS-Studio-view.coffee:7:21)
    at /packages/Atom-COS-Studio/lib/Atom-COS-Studio-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Atom-COS-Studio/lib/Atom-COS-Studio.coffee:1:21)
    at /packages/Atom-COS-Studio/lib/Atom-COS-Studio.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Non-Core Packages

```
Atom-COS-Studio 0.5.0 
language-cos 0.1.0 
vim-mode-plus 0.82.3 
```

**Comment by jonathanjbbr** [comment]
I am having the same error.
