### ISSUE TITLE
Cannot find module 'fsplus' (Failed to load the Atom-COS-Studio package)

### ISSUE THREAD

**Issue by jonathanjbbr** [UGroup/Atom-COS-Studio#37]
Following the steps in the readme (https://github.com/MDevelopmentGroup/Atom-COS-Studio) I've this error.
I have already tried "apm install --check".

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [Atom-COS-Studio](https://github.com/UGroup/Atom-COS-Studio) package 0.5.0

### Stack Trace

Failed to load the Atom-COS-Studio package

```
At Cannot find module 'fsplus'

Error: Cannot find module 'fsplus'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0-beta0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Atom-COS-Studio-master/lib/Atom-COS-Studio-view.coffee:4:5)
    at /packages/Atom-COS-Studio-master/lib/Atom-COS-Studio-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/Atom-COS-Studio-master/lib/Atom-COS-Studio.coffee:1:21)
    at /packages/Atom-COS-Studio-master/lib/Atom-COS-Studio.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
```

### Commands

```
```

### Non-Core Packages

```
Atom-COS-Studio 0.5.0 
```

**Comment by jonathanjbbr** [comment]
Duplicated.
